version: '3.8'


services:
  postgres:
    container_name: apiswebservice01
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestao-tarefas_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"


volumes:
  postgres: